// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_SeuGtpToCGHkzJH1wXFS59OoJOleSo',
    appId: '1:145701483873:web:2e22776708d1fa396b4120',
    messagingSenderId: '145701483873',
    projectId: 'acteen--flutter-app',
    authDomain: 'acteen--flutter-app.firebaseapp.com',
    storageBucket: 'acteen--flutter-app.appspot.com',
    measurementId: 'G-NKB634986Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwK9zO3-X2KfP_Hnisk8ZCGnfwh28ZVQ8',
    appId: '1:145701483873:android:c4b41f25d12ffdb96b4120',
    messagingSenderId: '145701483873',
    projectId: 'acteen--flutter-app',
    storageBucket: 'acteen--flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx8zdRaEMBNo1V1gUvn58dhIz0U-oksl0',
    appId: '1:145701483873:ios:42a339522ed17f1a6b4120',
    messagingSenderId: '145701483873',
    projectId: 'acteen--flutter-app',
    storageBucket: 'acteen--flutter-app.appspot.com',
    iosClientId: '145701483873-uhsjlq8i7160kiq18ue4dfeb9vlf9idj.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx8zdRaEMBNo1V1gUvn58dhIz0U-oksl0',
    appId: '1:145701483873:ios:ef67c289122c81b66b4120',
    messagingSenderId: '145701483873',
    projectId: 'acteen--flutter-app',
    storageBucket: 'acteen--flutter-app.appspot.com',
    iosClientId: '145701483873-p79rtm8j4mrbmulrr204bn4m0tm4mv9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
